// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmLT8P17bkglOxKOJKuthKXNFJsSqJ7jU',
    appId: '1:460955744718:web:d132b124112a52b6eb939f',
    messagingSenderId: '460955744718',
    projectId: 'chatapp-flutter-e7f3c',
    authDomain: 'chatapp-flutter-e7f3c.firebaseapp.com',
    storageBucket: 'chatapp-flutter-e7f3c.appspot.com',
    measurementId: 'G-4HPP6WCK3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRljN6-KX0B_ngmZ757Z3vs0Kz8ZmFkQo',
    appId: '1:460955744718:android:a1c3bced303a25bfeb939f',
    messagingSenderId: '460955744718',
    projectId: 'chatapp-flutter-e7f3c',
    storageBucket: 'chatapp-flutter-e7f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDySgB_9CYzV0zKDxET4SGEtVkIlgHUkpc',
    appId: '1:460955744718:ios:f391f957c0a73c0aeb939f',
    messagingSenderId: '460955744718',
    projectId: 'chatapp-flutter-e7f3c',
    storageBucket: 'chatapp-flutter-e7f3c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDySgB_9CYzV0zKDxET4SGEtVkIlgHUkpc',
    appId: '1:460955744718:ios:3d4eebbb2ca0de61eb939f',
    messagingSenderId: '460955744718',
    projectId: 'chatapp-flutter-e7f3c',
    storageBucket: 'chatapp-flutter-e7f3c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
